baseURL = "http://people.ku.edu/~s383u895"
languageCode = "en-us"
title = "Sagindyk Urazayev"
theme = "hugo-theme-nix"

[params]
  Name = "Sagindyk Urazayev"
  HeaderUsername = "s383u895"
  HeaderHostname = "people.ku.edu"
  About = "GIT d+ s+:- a? C++ UL++ P L+++ E+ W++ N o K- w+ O- M- V- PS PE+ Y+ PGP++ t- 5 X R+ tv++ b+++ DI D+ G++ e* h-- !r !y"
  ProfilePicture = "me.png"
  Email = "sagindyk.urazayev@ku.edu"
  Mobile = "+1-785-917-8451"
  GithubID = "thecsw"
  TelegramID = "thecsw"

[menu]
  [[menu.header]]
      identifier = "post"
      name = "posts"
      weight = 0
      url = "/posts"
  [[menu.header]]
      identifier = "archive"
      name = "archive"
      weight = 0
      url = "/archive"