baseURL = "http://people.ku.edu/~s383u895"
languageCode = "en-us"
title = "Sagindyk Urazayev"
theme = "hugo-theme-nix"

[params]
Name = "Sagindyk Urazayev"
HeaderUsername = "s383u895"
HeaderHostname = "people.ku.edu"
GnuPGFingerprint = "CCE2E27DAC465AC163013F1161BB674C628BB45B"
About = "GCS d s:-- a--- C++ UL++ P+ L+++ E+ W++ N++ o K w O M- V- PS+ PE+ Y+ PGP+ t- 5+ X R !tv b+++ DI D+ G++ e++ h-- !r y"
ProfilePicture = "me.png"
Email = "thecsw@ku.edu"
GithubID = "thecsw"
LinkedInID = "thecsw"
CvURL = "resume.pdf"

[menu]
  [[menu.header]]
      identifier = "about"
      name = "about.md"
      weight = 0
      url = "/about"